### ISSUE TITLE
Add README, LICENSE, CONTRIBUTING

### ISSUE THREAD

**Issue by ghost** [Zilliqa/docs#7]
This repo misses a README.md, a LICENSE.md and CONTRIBUTION instructions (as its not exactly clear if/how to contribute to the documents).

**Comment by bb111189** [comment]
This repo is intentionally left without any readme, license, and contribution as it is meant to use for Github pages for the team (only) to host resources. It is not meant for public contribution.

**Comment by ghost** [comment]
You seriously close this issue without taking action? This is unbelievable!

Even if a project is (for any reason) like this, you place 

* a README to clarify this (e.g. clarify that "no contributions are expected for those files")
* a LICENCSE to clarify which LICENSE those published(!) files have (instead letting visitors guessing or looking around).

**Comment by bb111189** [comment]
Reason as stated above. There is no licence int this repo. It is bunch of non core related resource that is meant for website. Each single item can have different licence. Please stop forcing developer to do what you wish and respect the difference in our opinion on how to manage a repo.

**Comment by ghost** [comment]
Respect? People which apply censorship do not deserve respect at all.

One last question: why are you refusing to add a README to clarify all this?

**Comment by bb111189** [comment]
I am sad to see such disrespect. If you continue to unable to respect the difference in opinion, and forcing us to go your way, we may have to ban you from all repo. We expect basic respect, who you admit here that you are disrespectful.

Every single docs in this repo is a hosted resource under `docs.zilliqa.com` and copyright by us. It serve as a repo for us to easily hosts documents and sharing on any medium we like to. Having a hosted resource such as readme may be misused by others to misrepresent us in a different context than it is intended to be.

We keep this repo open so that people who do not have the url or lost the exact url, still can access it. 

Please note that not all public repo need to have readme/license. It is up to the owner of the resources to determine how it is managed. 

Also, before you say why docs.zilliqa.com is without the index page. It is intended as it is for security reasons.
